name: molkky_match
description: Une appli pour gérer le score de vos parties de Mölkky !
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.4.0
  google_fonts: ^5.0.0
  flutter_blurhash: ^0.7.0
  sqflite: ^2.2.8+4
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - lib/screens/rules/doc/

  fonts:
    - family: RailsBroken
      fonts:
        - asset: assets/fonts/RailsBroken.otf
    - family: RailsDisplay
      fonts:
        - asset: assets/fonts/RailsDisplay.otf
